### ISSUE TITLE
Suggestion re: original blog post

### ISSUE THREAD

**Issue by lunelson** [amcss/amcss.github.io#7]
I'm a big fan of this concept but I want to point something out re: @geelen's original post, even though it was 18 months ago:

It's argued there that 'single-class' BEM is difficult to override because there's no effective way to select the base class. However, given the example of wanting to select all `btn` base-classed elements, the selector `.btn, [class*='btn--']` actually does the trick. The attribute-selector pattern mentioned, `[class^='btn']`, is a 'starts-with' pattern; but the fact that BEM uses a `--` after every base class means you can actually use a 'substring' pattern with accuracy, and not be affected by the order of the classes. In Sass, I write a lot of styles like this (one of the few real use-cases for `@extend` imo):

``` scss
[class*='base--'] { @extend .base; ]
.base { /* base styles */ }
.base--mod { /* mod styles */ }
```

**Comment by ShaggyDude** [comment]
I agree with what BEM Is trying to do but absolutely hate the __syntax--
I think this would be even more powerful combined with a utility class library like tachyons (verbose edition) and @extend.

[Button] {
  @extends .border;
  @extends .rounded;
  & .is-active {
    @extends .active;
  }
}
